#!/usr/bin/env python3
"""Validate the actual D20 DM-agent turn, not just passthrough health.

Acceptance criteria:
- /dm/health reports Hermes mode and runtime_ready=true.
- Fresh /dm/character succeeds.
- Fresh /dm/turn without caller-supplied session_id returns 200 and a non-null
  session_id generated by the narrator path.
- Response is valid DMResponse shape with narration/mechanics/trace.
- Container logs should not show direct-mode 401 fallback during the checked turn
  (checked manually in deployment audits; this script is HTTP-only).
"""
from __future__ import annotations

import argparse
import json
import random
import string
import sys
import time
import urllib.error
import urllib.request


def request(base: str, method: str, path: str, payload: dict | None = None, timeout: int = 90):
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(
        base.rstrip("/") + path,
        data=data,
        headers={"Content-Type": "application/json"},
        method=method,
    )
    started = time.time()
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            text = resp.read().decode("utf-8", "replace")
            return resp.status, time.time() - started, text
    except urllib.error.HTTPError as exc:
        text = exc.read().decode("utf-8", "replace")
        return exc.code, time.time() - started, text


def fail(message: str):
    print(f"FAIL: {message}")
    sys.exit(1)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", default="https://agentdungeon.com")
    parser.add_argument("--max-turn-seconds", type=float, default=120.0)
    args = parser.parse_args()

    status, elapsed, text = request(args.base, "GET", "/dm/health", timeout=20)
    if status != 200:
        fail(f"/dm/health returned {status}: {text[:500]}")
    health = json.loads(text)
    narrator = health.get("narrator", {})
    print("DM health:", json.dumps(narrator, indent=2, sort_keys=True))
    if narrator.get("mode") != "hermes":
        fail(f"narrator.mode must be hermes, got {narrator.get('mode')!r}")
    if narrator.get("runtime_ready") is not True:
        fail("narrator.runtime_ready must be true for actual DM-agent turn")

    suffix = "".join(random.choice(string.ascii_lowercase) for _ in range(6))
    payload = {"name": f"ActualDM{suffix}", "race": "Human", "class": "Fighter", "background": "Soldier"}
    status, elapsed, text = request(args.base, "POST", "/dm/character", payload, timeout=60)
    if status != 200:
        fail(f"/dm/character returned {status}: {text[:500]}")
    character = json.loads(text)
    char_id = character.get("id")
    if not char_id:
        fail("/dm/character did not return id")
    print("Created character:", char_id)

    turn_payload = {"character_id": char_id, "message": "look around and describe what I notice"}
    status, elapsed, text = request(args.base, "POST", "/dm/turn", turn_payload, timeout=150)
    print(f"/dm/turn status={status} elapsed={elapsed:.2f}s")
    if status != 200:
        fail(f"/dm/turn returned {status}: {text[:1000]}")
    if elapsed > args.max_turn_seconds:
        fail(f"/dm/turn exceeded {args.max_turn_seconds}s: {elapsed:.2f}s")
    turn = json.loads(text)
    if not turn.get("session_id"):
        fail("/dm/turn returned null/empty session_id; Hermes session was not established")
    scene = (turn.get("narration") or {}).get("scene")
    if not scene:
        fail("/dm/turn returned empty narration.scene")
    trace = turn.get("server_trace") or {}
    print("Session:", turn["session_id"])
    print("Endpoint:", trace.get("server_endpoint_called"))
    print("Scene:", scene[:300])
    print("OK: actual DM-agent turn passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
